baseurl: "https://drivechain.win/"
title: "Drivechain for the win"
theme: "zen"
languageCode: "en-US"       # Set your language code (only needed for none multilingual sites).
pluralizelisttitles: false
removePathAccents: true

params:
  contact: "contact@drivechain.win"
  dateformat: ""            # Set the date format, default to "2 January, 2006"
  description: "Collection of media related to Drivechain"           # Set site description, used in meta tags and JSON-LD
  favicon: ""               # Relative path to favicon in json feed, no leading slash.
  feedlinks: true           # Show feed links in the footer.
  icon: ""                  # Relative path to icon in json feed and JSON-LD, no leading slash.
  image: ""                 # Relative path to site image in JSON-LD, no leading slash.
  imageMaxWidth: ""         # Max width for images added via figure shortcode.
  jquery: true              # Add jQuery
  languageDir: ""           # Set ltr or rtl, defaults to ltr.
  logo: false               # Turn off the logo.
  logoPath:                 # Relative path to site logo, defaults to "images/logo.png", no leading slash.
  logoWidth:                # Set logo width, defaults to none.
  mainSections:             # The sections you want to have listed on the front page.
  mobileMenu: true          # Turn on a mobile menu on small screens, default false.
  poweredby: true           # Show powered by hugo in footer

  realfavicongenerator:     # If full set of favicons, site manifest etc. exists, default false.
  searchLimit: 20           # Max number of search hits, default 20.
  sidebar: false             # Show a sidebar to the right, default false.
  submitted: true           # Show author and date information for a post.
  themeColor:               # Hex color value, used in meta tags, default "#ffffff".

  podcast:
    title: "Drivechain"                 # * Feed title, defaults to site title (iTunes).
    description: "Everything about Drivechain"           # * Feed description/summary, defaults to  site description (iTunes).
    image: "logo.webp"                 # * Feed image, place inside assets directory (iTunes).
    category:
      name:  "Technology"               # * Feed category (iTunes).
      subcategories: ["Blockchain"]     # Feed sub category (iTunes).
    explicit: false    # Feed explicit setting, default to false (iTunes).
    author: "Drivechain"                # Feed author (iTunes).
    owner:
      name: "Drivechain"                # Feed owner name (iTunes).
      email: "contact@drivechain.win"               # Feed owner e-mail (iTunes).
    lang: "en-US"                  # Feed language, defaults to site language (iTunes).
    block: no           # Block the feed from iTunes, default to no (iTunes).
    complete: no        # Set the feed as complete, defaults to no (iTunes).
    type: episodic   # Podcast type, defaults to episodic (iTunes).
    newfeed:                # Are you moving? Set the new feed url here (iTunes).
    cdn:                    # CDN url, no slash on end (https://cdn.example.org).
    local: false            # Are the audio files local (true) or remote (false), default to true.
    preload: metadata # Set on the HTML5 audio tag, defaults to "metadata".

outputFormats:
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true

outputs:
  home: ["HTML", "SearchIndex"]